### ISSUE TITLE
Paper Issue tracking

### ISSUE THREAD

**Issue by isolatedinformation** [latticesurgery-com/general-issue-tracker#5]
Just a place to maintain a to-do list for tracking tasks remaining for writing the paper!
- [ ] Circuit diagrams
	- [x] R_z gate identity 
- [ ] Clean up references to be of uniform! 
- [ ] What level of references should be made? ex: Citing OpenQASM ?
- [ ] Figure 4
- [x] Figure 7
- [x] Figure 8 after latest pr updating `partition_gate_sequence`
	- [ ] Change axis names 
- [ ] Section 2!

**Comment by gwwatkin** [comment]
I think we achieved success by submitting this paper!
